/**
 * svg.js — SVG generation and export module for ClearCut
 *
 * Exports (on window):
 *   window.ClearCutSVG.generateSVG(contours, imageW, imageH, sheetWIn, sheetHIn) → string
 *   window.ClearCutSVG.downloadSVG(svgString, filename)
 *   window.ClearCutSVG.applyPaddingToContour(contour, paddingPx) → contour
 */

const ClearCutSVG = (() => {

  // Cricut Design Space SVG coordinate system:
  //   1 SVG user unit = 1/72 inch  (72 dpi)
  //   Standard mat: 12" × 12"  = 864 × 864 SVG units
  const SVG_DPI        = 72;
  const MAT_W_IN       = 12;
  const MAT_H_IN       = 12;
  const MAT_W_UNITS    = MAT_W_IN * SVG_DPI;   // 864
  const MAT_H_UNITS    = MAT_H_IN * SVG_DPI;   // 864

  // ── Path generation ───────────────────────────────────────────────────────

  /**
   * Convert a contour's points (in image pixel coordinates) to an SVG <path> d= string.
   *
   * @param {{x,y}[]} points    – pixel-space contour points
   * @param {number}  scale     – px → SVG unit scale factor
   * @returns {string}
   */
  function contourToPathD(points, scale) {
    if (!points || points.length < 2) return '';
    const fmt = n => (n * scale).toFixed(3);
    const [first, ...rest] = points;
    const parts = [`M ${fmt(first.x)},${fmt(first.y)}`];
    for (const pt of rest) {
      parts.push(`L ${fmt(pt.x)},${fmt(pt.y)}`);
    }
    parts.push('Z');
    return parts.join(' ');
  }

  // ── Padding (outward offset) ──────────────────────────────────────────────

  /**
   * Compute the centroid of a polygon.
   */
  function centroid(points) {
    let cx = 0, cy = 0;
    for (const p of points) { cx += p.x; cy += p.y; }
    return { x: cx / points.length, y: cy / points.length };
  }

  /**
   * Expand a contour outward by `paddingPx` pixels by pushing each vertex
   * away from the centroid.
   *
   * @param {{points,bounds,area,enabled}} contour
   * @param {number} paddingPx
   * @returns new contour object with expanded points
   */
  function applyPaddingToContour(contour, paddingPx) {
    if (!paddingPx || paddingPx <= 0) return contour;
    const c  = centroid(contour.points);
    const pts = contour.points.map(p => {
      const dx = p.x - c.x;
      const dy = p.y - c.y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (dist < 0.001) return p;
      return {
        x: p.x + (dx / dist) * paddingPx,
        y: p.y + (dy / dist) * paddingPx,
      };
    });
    return { ...contour, points: pts };
  }

  // ── SVG generation ────────────────────────────────────────────────────────

  /**
   * Generate a Cricut-compatible SVG string from the detected contours.
   *
   * @param {Array}  contours    – array of contour objects (only enabled ones are rendered)
   * @param {number} imageW      – source image width in pixels
   * @param {number} imageH      – source image height in pixels
   * @param {number} sheetWIn    – physical sheet width in inches
   * @param {number} sheetHIn    – physical sheet height in inches
   * @param {number} paddingMm   – outward padding in mm (applied before scaling)
   * @returns {string}           – SVG string ready to save as .svg
   */
  function generateSVG(contours, imageW, imageH, sheetWIn, sheetHIn, paddingMm = 0) {
    // Compute px per inch based on the sheet width
    const pxPerInch = imageW / sheetWIn;

    // SVG scale: 1 px → SVG units
    const scale = SVG_DPI / pxPerInch;

    // Padding in pixels
    const paddingPx = paddingMm > 0 ? (paddingMm / 25.4) * pxPerInch : 0;

    // Final SVG canvas dimensions — fit sheet inside the 12×12 mat
    const sheetSVGW = (sheetWIn  * SVG_DPI).toFixed(3);
    const sheetSVGH = (sheetHIn  * SVG_DPI).toFixed(3);

    // Build path elements
    const paths = contours
      .filter(c => c.enabled)
      .map((c, i) => {
        const padded = applyPaddingToContour(c, paddingPx);
        const d      = contourToPathD(padded.points, scale);
        if (!d) return '';
        return `  <path
    id="shape-${i}"
    d="${d}"
    fill="none"
    stroke="#000000"
    stroke-width="0.01in"
    vector-effect="non-scaling-stroke"
  />`;
      })
      .filter(Boolean)
      .join('\n');

    const enabledCount = contours.filter(c => c.enabled).length;

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ClearCut — https://github.com/jcxsofa/ClearCut -->
<!-- Sheet: ${sheetWIn}" × ${sheetHIn}"  |  Shapes: ${enabledCount} -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${sheetSVGW}"
  height="${sheetSVGH}"
  viewBox="0 0 ${sheetSVGW} ${sheetSVGH}"
>
  <!-- Mat boundary (for reference) -->
  <rect
    id="mat-boundary"
    x="0" y="0"
    width="${sheetSVGW}" height="${sheetSVGH}"
    fill="none"
    stroke="#cccccc"
    stroke-width="0.5"
    stroke-dasharray="4,4"
  />
${paths}
</svg>`;
  }

  // ── Download ──────────────────────────────────────────────────────────────

  /**
   * Trigger a browser download of the SVG string as a .svg file.
   * @param {string} svgString
   * @param {string} filename
   */
  function downloadSVG(svgString, filename = 'ClearCut-cutfile.svg') {
    const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  }

  // ── Canvas preview rendering ──────────────────────────────────────────────

  /**
   * Draw contour outlines onto a canvas, overlaid on the source image.
   *
   * @param {HTMLCanvasElement}  canvas
   * @param {HTMLImageElement}   imgEl      – source image to draw as background
   * @param {Array}              contours   – contour objects
   * @param {number}             paddingPx  – padding already applied (for display)
   * @param {number|null}        hoverIdx   – index of hovered contour (or null)
   */
  function drawPreview(canvas, imgEl, contours, paddingPx = 0, hoverIdx = null) {
    // Fit canvas to container
    const container = canvas.parentElement;
    const maxW      = container ? container.clientWidth  : 680;
    const maxH      = 480;

    const imgW   = imgEl.naturalWidth  || imgEl.width;
    const imgH   = imgEl.naturalHeight || imgEl.height;
    const ratio  = Math.min(maxW / imgW, maxH / imgH, 1);

    canvas.width  = Math.round(imgW * ratio);
    canvas.height = Math.round(imgH * ratio);

    const ctx = canvas.getContext('2d');
    ctx.drawImage(imgEl, 0, 0, canvas.width, canvas.height);

    // Draw each contour
    contours.forEach((c, idx) => {
      const padded = applyPaddingToContour(c, paddingPx);
      const pts    = padded.points;
      if (!pts || pts.length < 2) return;

      ctx.beginPath();
      ctx.moveTo(pts[0].x * ratio, pts[0].y * ratio);
      for (let i = 1; i < pts.length; i++) {
        ctx.lineTo(pts[i].x * ratio, pts[i].y * ratio);
      }
      ctx.closePath();

      if (!c.enabled) {
        ctx.strokeStyle = 'rgba(150,150,150,0.5)';
        ctx.lineWidth   = 1;
        ctx.setLineDash([4, 4]);
      } else if (idx === hoverIdx) {
        ctx.strokeStyle = '#ffcc00';
        ctx.lineWidth   = 3;
        ctx.setLineDash([]);
      } else {
        ctx.strokeStyle = '#00ff66';
        ctx.lineWidth   = 2;
        ctx.setLineDash([]);
      }
      ctx.stroke();
      ctx.setLineDash([]);

      // Dim disabled shapes
      if (!c.enabled) {
        ctx.fillStyle = 'rgba(0,0,0,0.25)';
        ctx.fill();
      }
    });

    return ratio;
  }

  // ── Public API ────────────────────────────────────────────────────────────
  return {
    generateSVG,
    downloadSVG,
    applyPaddingToContour,
    drawPreview,
    SVG_DPI,
    MAT_W_IN,
    MAT_H_IN,
  };

})();

window.ClearCutSVG = ClearCutSVG;
